runtime: nodejs18
env: standard
instance_class: F1

env_variables:
  NODE_ENV: "production"
  PORT: "8080"

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 2
  target_cpu_utilization: 0.65
