services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./database.sqlite:/usr/src/app/database.sqlite
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]